### ISSUE TITLE
I can't find the slackMessage:responseToken 

### ISSUE THREAD

**Issue by eater** [fjeldstad/SlackCommander#1]
Slack may have changed the Incoming Webhooks setup, but I don't see a token I can use for this.

**Comment by fjeldstad** [comment]
Wow you are completely right, seems like they have decided to include the token as part of the url instead. I had no idea, but then it was a while since set up one (and they seem to be backwards-compatible).

I will update the code + setup instructions when I get the chance, but in the meantime you _could_ try using the last segment of the webhook url as response token and see if that works.
